if: (type = push AND branch IN (master,)) OR (type = pull_request AND NOT branch =~ /no-ci/)
language: python
python:
  - "3.7"
install:
  - pip install --upgrade pip
  - pip install poetry
  - poetry install -v
script:
  - pytest -v
#  - NUMBA_DISABLE_JIT=1 pytest -v --cov=wildwood tests/
# after_success: coveralls
cache:
  pip: true
  directories:
    - $HOME/wildwood
